### ISSUE TITLE
Gazebo Support

### ISSUE THREAD

**Issue by bektaskemal** [RobotnikAutomation/widowx_turret#1]
Hi,
I wonder if it is possible to use this package in Gazebo simulation without using the real Arbotix board?

**Comment by jacobbreen25** [comment]
Hello, using a ros launch file, you can simulate this in Gazebo using the urdf.xacro file in widowx_turret_description/robots.

**Comment by jacobbreen25** [comment]
> Hi, I wonder if it is possible to use this package in Gazebo simulation without using the real Arbotix board?



> Hi, I wonder if it is possible to use this package in Gazebo simulation without using the real Arbotix board?



> Hi, I wonder if it is possible to use this package in Gazebo simulation without using the real Arbotix board?

Hello, using a ros launch file, you can simulate this in Gazebo using the urdf.xacro file in widowx_turret_description/robots.
